import assert from "node:assert/strict";
import { mkdir, mkdtemp, rm, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { discoverSshAliases, lexArguments, parseDirective } from "../src/core/ssh-config.js";

async function home(t: test.TestContext): Promise<string> { const root = await mkdtemp(join(tmpdir(), "ssh-picker-")); t.after(() => rm(root, { recursive: true, force: true })); await mkdir(join(root, ".ssh"), { recursive: true }); return root; }
test("lexes quoted, escaped and commented directives", () => { assert.deepEqual(parseDirective('  HoSt = "alpha" beta\\ host # no'), { keyword: "host", args: ["alpha", "beta host"] }); assert.deepEqual(lexArguments("'a#b' c"), ["a#b", "c"]); assert.throws(() => lexArguments("'oops"), /unterminated/); });
test("discovers mixed literals, excludes patterns and deduplicates case-insensitively", async (t) => { const root = await home(t); await writeFile(join(root, ".ssh/config"), "Host build *.corp !old other build BUILD\nHost -bad foo? bar[0]\n"); const found = await discoverSshAliases({ home: root }); assert.deepEqual(found.aliases.map((a) => a.name), ["build", "other"]); assert.equal(found.aliases[0]?.sources.length, 3); });
test("expands relative, tilde and sorted nested glob includes and guards cycles", async (t) => { const root = await home(t); await mkdir(join(root, ".ssh/conf.d")); await writeFile(join(root, ".ssh/config"), "Include conf.d/*.conf ~/.ssh/extra\nHost root\n"); await writeFile(join(root, ".ssh/conf.d/b.conf"), "Host beta\n"); await writeFile(join(root, ".ssh/conf.d/a.conf"), "Include config\nHost alpha\n"); await writeFile(join(root, ".ssh/extra"), "Host extra\n"); const found = await discoverSshAliases({ home: root }); assert.deepEqual(found.aliases.map((a) => a.name), ["alpha", "beta", "extra", "root"]); assert.ok(found.warnings.some((w) => w.includes("cycle"))); });
test("missing root is an empty state and missing optional globs are harmless", async (t) => { const root = await home(t); let found = await discoverSshAliases({ home: root }); assert.equal(found.rootExists, false); await writeFile(join(root, ".ssh/config"), "Include missing/*.conf\nHost yes\n"); found = await discoverSshAliases({ home: root }); assert.deepEqual(found.aliases.map((a) => a.name), ["yes"]); assert.deepEqual(found.warnings, []); });
test("does not execute Match exec and warns on dynamic includes", async (t) => { const root = await home(t); const marker = join(root, "owned"); await writeFile(join(root, ".ssh/config"), `Match exec "touch ${marker}"\nHost safe\nInclude %h/config\n`); const found = await discoverSshAliases({ home: root }); assert.deepEqual(found.aliases.map((a) => a.name), ["safe"]); assert.match(found.warnings[0] ?? "", /unsupported/); });
